ntuple_path: "root://cmsdcache-kit-disk.gridka.de//store/user/amonsch/CROWN/ntuples/ff_and_cr_production_2018UL_mt__2025-11-03_wo_syst_v1/CROWNRun"
output_path: /ceph/amonsch/FFmethod/smhtt_ul/ff_and_cr_production_2018UL_mt__2025-08-21_wo_syst_v2_2025-11-03
friends: ["fastmtt_v1"]
file_path: /ceph/amonsch/FFmethod/smhtt_ul/ff_and_cr_production_2018UL_mt__2025-08-21_wo_syst_v2_2025-11-03

workdir_name: extended_corrections_set_with_applied_es_corrections

era: '2018'
tree: ntuple
nanoAOD_version: "nanoAOD_v9"

tau_vs_jet_wps:
  - VVLoose
  - VLoose
  - Loose
  - Medium
  - Tight
  - VTight
tau_vs_jet_wgt_wps:
  - Loose
  - Medium
  - Tight
  - VTight

use_embedding: true
use_center_of_mass_bins: true
