channel: mt
processes:
  DYjets:
    samples:
      - DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
      - DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
      - DY1JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
      - DY2JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
      - DY3JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
      - DY4JetsToLL_M-50_MatchEWPDG20_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
    tau_gen_modes:
      - J
      - T
      - L
  ST:
    samples:
      - ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8_RunIISummer20UL18NanoAODv9-106X
      - ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8_RunIISummer20UL18NanoAODv9-106X
      - ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
      - ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
    tau_gen_modes:
      - J
      - T
      - L
  Wjets:
    samples:
      - WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
      - W1JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
      - W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
      - W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
      - W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8_RunIISummer20UL18NanoAODv9-106X
    tau_gen_modes:
      - all
  data:
    samples:
      - SingleMuon_Run2018A-UL2018_GT36
      - SingleMuon_Run2018B-UL2018_GT36
      - SingleMuon_Run2018C-UL2018_GT36
      - SingleMuon_Run2018D-UL2018_GT36
    tau_gen_modes:
      - all
  diboson:
    samples:
      - ZZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X
      - WW_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X
      - WZ_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X
    tau_gen_modes:
      - J
      - T
      - L
  embedding:
    samples:
      - TauEmbedding-MuTauFinalState_Run2018A-UL2018
      - TauEmbedding-MuTauFinalState_Run2018B-UL2018
      - TauEmbedding-MuTauFinalState_Run2018C-UL2018
      - TauEmbedding-MuTauFinalState_Run2018D-UL2018
    tau_gen_modes:
      - all
  ttbar:
    samples:
      - TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
      - TTToHadronic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
      - TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X
    tau_gen_modes:
      - J
      - T
      - L

event_selection:
  had_tau_decay_mode: (tau_decaymode_2 == 0) || (tau_decaymode_2 == 1) || (tau_decaymode_2 == 10) || (tau_decaymode_2 == 11)
  had_tau_id_vs_ele: id_tau_vsEle_VVLoose_2 > 0.5
  had_tau_id_vs_mu: id_tau_vsMu_Tight_2 > 0.5
  had_tau_pt: pt_2 > 30
  lep_pt: ((pt_1 > 25) && ((trg_single_mu27 > 0.5) || (trg_single_mu24 > 0.5)))
  nbtag: (nbtag >= 0)
mc_weights:
  Top_pt_reweighting: topPtReweightWeight
  Z_pt_reweighting: ZPtMassReweightWeight
  generator:
    stitching:
      - DYjets
      - Wjets
  had_tau_id_vs_ele: (gen_match_2==5) * ((id_tau_vsEle_VVLoose_2>0.5)*id_wgt_tau_vsEle_VVLoose_2 + (id_tau_vsEle_VVLoose_2<0.5)) + (gen_match_2!=5)
  had_tau_id_vs_mu: (gen_match_2==5) * ((id_tau_vsMu_Tight_2>0.5)*id_wgt_tau_vsMu_Tight_2 + (id_tau_vsMu_Tight_2<0.5)) + (gen_match_2!=5)
  lep_id: id_wgt_mu_1
  lep_iso: iso_wgt_mu_1
  lumi: ""
  pileup: puweight
  single_trigger: trg_wgt_single_mu24ormu27
emb_weights:
  generator: (emb_genweight * emb_idsel_wgt_1 * emb_idsel_wgt_2 * emb_triggersel_wgt)
  lep_id: id_wgt_mu_1
  lep_iso: iso_wgt_mu_1
  single_trigger: trg_wgt_single_mu24ormu27

output_features:
  - mt_1
  - dilepton_veto
  - weight
  - btag_weight
  - q_1
  - pt_2
  - q_2
  - gen_match_2
  - pt_1
  - extramuon_veto
  - extraelec_veto
  - dimuon_veto
  - tau_decaymode_1
  - tau_decaymode_2
  - mass_1
  - mass_2
  - iso_1
  - iso_2
  - beta_1
  - beta_2
  - bphi_1
  - bphi_2
  - bpt_1
  - bpt_2
  - btag_value_1
  - btag_value_2
  - deltaEta_12j1
  - deltaEta_12j2
  - deltaEta_12jj
  - deltaEta_1j1
  - deltaEta_1j2
  - deltaEta_2j1
  - deltaEta_2j2
  - deltaEta_ditaupair
  - deltaEta_jj
  - deltaPhi_12j1
  - deltaPhi_12j2
  - deltaPhi_12jj
  - deltaPhi_1j1
  - deltaPhi_1j2
  - deltaPhi_2j1
  - deltaPhi_2j2
  - deltaPhi_ditaupair
  - deltaPhi_jj
  - deltaR_12j1
  - deltaR_12j2
  - deltaR_12jj
  - deltaR_1j1
  - deltaR_1j2
  - deltaR_2j1
  - deltaR_2j2
  - deltaR_ditaupair
  - deltaR_jj
  - eta_1
  - eta_2
  - jeta_1
  - jeta_2
  - jphi_1
  - jphi_2
  - jpt_1
  - jpt_2
  - m_vis
  - met
  - metphi
  - mjj
  - mt_2
  - mt_tot
  - nbtag
  - njets
  - pfmet
  - pfmetphi
  - phi_1
  - phi_2
  - pt_dijet
  - pt_tt
  - pt_ttjj
  - pt_vis
  - eta_fastmtt
  - m_fastmtt
  - phi_fastmtt
  - pt_fastmtt
