# This is an example config containing information for the FF corrections

channel: "tt" # options are et, mt, tt

target_processes:
    QCD:
        non_closure:
            pt_2:
                var_dependence: "pt_2"
                var_bins: [40,50,60,70,80,100]
            tau_decaymode_1:
                var_dependence: "tau_decaymode_1"
                var_bins: [-0.5, 0.5, 1.5, 9.5, 10.5, 11.5]
            mass_1:
                var_dependence: "mass_1"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]

        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,50,70,90,110,130,150,170,200,250]
            SRlike_cuts:
                had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
            ARlike_cuts:
                had_tau_id_vs_jet_2: "(id_tau_vsJet_VVVLoose_2 > 0.5) && (id_tau_vsJet_Medium_2 < 0.5)"
            AR_SR_cuts:
                tau_pair_sign: "(q_1*q_2) < 0"
                jj_selection: "1 == 1" # remove jj selection, to be replaced with actual bb selection
                bb_selection: "(nbtag >= 1) && (bpair_pt_1 > 20) && (bpair_pt_2 > 20)"

    QCD_subleading:
        non_closure:
            pt_1:
                var_dependence: "pt_1"
                var_bins: [40,55,70,85,100,150]
            tau_decaymode_2:
                var_dependence: "tau_decaymode_2"
                var_bins: [-0.5, 0.5, 1.5, 9.5, 10.5, 11.5]
            mass_2:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]

        DR_SR:
            var_dependence: "m_vis"
            var_bins: [0,50,70,90,110,130,150,170,200,250]
            SRlike_cuts:
                had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            ARlike_cuts:
                had_tau_id_vs_jet_1: "(id_tau_vsJet_VVVLoose_1 > 0.5) && (id_tau_vsJet_Medium_1 < 0.5)"
            AR_SR_cuts:
                tau_pair_sign: "(q_1*q_2) < 0"
                jj_selection: "1 == 1" # remove jj selection, to be replaced with actual bb selection
                bb_selection: "(nbtag >= 1) && (bpair_pt_1 > 20) && (bpair_pt_2 > 20)"

    ttbar:
        non_closure:
            pt_2:
                var_dependence: "pt_2"
                var_bins: [40,50,60,70,80,100]
            tau_decaymode_1:
                var_dependence: "tau_decaymode_1"
                var_bins: [-0.5, 0.5, 1.5, 9.5, 10.5, 11.5]
            mass_1:
                var_dependence: "mass_1"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]

    ttbar_subleading:
        non_closure:
            pt_1:
                var_dependence: "pt_1"
                var_bins: [40,55,70,85,100,150]
            tau_decaymode_2:
                var_dependence: "tau_decaymode_2"
                var_bins: [-0.5, 0.5, 1.5, 9.5, 10.5, 11.5]
            mass_2:
                var_dependence: "mass_2"
                var_bins: [0.,0.2,0.5,0.8,1.1,1.4,2.]

