channel: et
processes:
  DYjets:
    samples:
      - DYto2E_Bin-MLL-10to50_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2E_Bin-MLL-120to200_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2E_Bin-MLL-1500to2500_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2E_Bin-MLL-200to400_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2E_Bin-MLL-2500to4000_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2E_Bin-MLL-4000to6000_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2E_Bin-MLL-400to800_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2E_Bin-MLL-50to120_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2E_Bin-MLL-6000_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2E_Bin-MLL-800to1500_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Mu_Bin-MLL-10to50_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Mu_Bin-MLL-120to200_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Mu_Bin-MLL-1500to2500_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Mu_Bin-MLL-200to400_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Mu_Bin-MLL-2500to4000_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Mu_Bin-MLL-4000to6000_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Mu_Bin-MLL-400to800_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Mu_Bin-MLL-50to120_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Mu_Bin-MLL-6000_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Mu_Bin-MLL-800to1500_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Tau_Bin-MLL-10to50_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Tau_Bin-MLL-120to200_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Tau_Bin-MLL-1500to2500_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Tau_Bin-MLL-200to400_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Tau_Bin-MLL-2500to4000_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Tau_Bin-MLL-4000to6000_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Tau_Bin-MLL-400to800_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Tau_Bin-MLL-50to120_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Tau_Bin-MLL-6000_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - DYto2Tau_Bin-MLL-800to1500_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
    tau_gen_modes:
      - J
      - T
      - L
  ST:
    samples:
      - TBbarQto2Q-t-channel-4FS_TuneCP5_13p6TeV_powheg-madspin-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TBbarQtoLNu-t-channel-4FS_TuneCP5_13p6TeV_powheg-madspin-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TWminusto4Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TbarBQto2Q-t-channel-4FS_TuneCP5_13p6TeV_powheg-madspin-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TbarBQtoLNu-t-channel-4FS_TuneCP5_13p6TeV_powheg-madspin-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TbarWplusto4Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
    tau_gen_modes:
      - J
      - T
      - L
  Wjets:
    samples:
      - WtoENu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_RunIII2025Summer24NanoAODv15-150X
      - WtoMuNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_RunIII2025Summer24NanoAODv15-150X
      - WtoTauNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8_RunIII2025Summer24NanoAODv15-150X
    tau_gen_modes:
      - all
  data:
    samples:
      - EGamma0_Run2025C-PromptReco-v1
      - EGamma0_Run2025C-PromptReco-v2
      - EGamma0_Run2025D-PromptReco-v1
      - EGamma0_Run2025E-PromptReco-v1
      - EGamma0_Run2025F-PromptReco-v1
      - EGamma0_Run2025F-PromptReco-v2
      - EGamma0_Run2025G-PromptReco-v1
      - EGamma1_Run2025C-PromptReco-v1
      - EGamma1_Run2025C-PromptReco-v2
      - EGamma1_Run2025D-PromptReco-v1
      - EGamma1_Run2025E-PromptReco-v1
      - EGamma1_Run2025F-PromptReco-v1
      - EGamma1_Run2025F-PromptReco-v2
      - EGamma1_Run2025G-PromptReco-v1
      - EGamma2_Run2025C-PromptReco-v1
      - EGamma2_Run2025C-PromptReco-v2
      - EGamma2_Run2025D-PromptReco-v1
      - EGamma2_Run2025E-PromptReco-v1
      - EGamma2_Run2025F-PromptReco-v1
      - EGamma2_Run2025F-PromptReco-v2
      - EGamma2_Run2025G-PromptReco-v1
      - EGamma3_Run2025C-PromptReco-v1
      - EGamma3_Run2025C-PromptReco-v2
      - EGamma3_Run2025D-PromptReco-v1
      - EGamma3_Run2025E-PromptReco-v1
      - EGamma3_Run2025F-PromptReco-v1
      - EGamma3_Run2025F-PromptReco-v2
      - EGamma3_Run2025G-PromptReco-v1
    tau_gen_modes:
      - all
  diboson:
    samples:
      - WWto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - WWto4Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - WWtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - WZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - WZtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - ZZto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - ZZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - ZZto2Nu2Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - ZZto4L_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
    tau_gen_modes:
      - J
      - T
      - L
  ttbar:
    samples:
      - TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TTto4Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
      - TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8_RunIII2025Summer24NanoAODv15-150X
    tau_gen_modes:
      - J
      - T
      - L
event_selection:
  had_tau_decay_mode: (tau_decaymode_2 == 0) || (tau_decaymode_2 == 1) || (tau_decaymode_2 == 10) || (tau_decaymode_2 == 11)
  had_tau_id_vs_ele: id_tau_vsEle_Tight_2 > 0.5
  had_tau_id_vs_mu: id_tau_vsMu_VLoose_2 > 0.5
  had_tau_pt: pt_2 > 20
  lep_pt: ((pt_1 > 32) && (trg_single_ele30 > 0.5))
  jet_veto: (Jet_vetomap < 0.5)
  met_mask: (met_mask > 0.5)
mc_weights:
  Top_pt_reweighting: topPtReweightWeight
  Z_pt_reweighting: zPtReweightWeight
  generator: ""
    #stitching:
    #  - DYjets
    #  - Wjets
  had_tau_id_vs_ele: (gen_match_2==5) * ((id_tau_vsEle_Tight_2>0.5)*id_wgt_tau_vsEle_Tight_2 + (id_tau_vsEle_Tight_2<0.5)) + (gen_match_2!=5)
  had_tau_id_vs_mu: (gen_match_2==5) * ((id_tau_vsMu_VLoose_2>0.5)*id_wgt_tau_vsMu_VLoose_2 + (id_tau_vsMu_VLoose_2<0.5)) + (gen_match_2!=5)
  lep_id: id_wgt_ele_wp90iso_1
  lep_iso:  1 #iso_wgt_ele_1
  lumi: ""
  pileup: puweight
  single_trigger: trg_wgt_single_ele30
#emb_weights:
#  generator: emb_genweight * emb_idsel_wgt_1 * emb_idsel_wgt_2 * emb_triggersel_wgt
#  lep_id: id_wgt_ele_1
#  lep_iso: iso_wgt_ele_1
#  single_trigger: trg_wgt_single_ele32orele35

output_features:
  - mt_1
  - dimuon_veto
  - weight
  - btag_weight
  - q_1
  - pt_2
  - q_2
  - gen_match_2
  - pt_1
  - extramuon_veto
  - extraelec_veto
  - dilepton_veto
  - tau_decaymode_1
  - tau_decaymode_2
  - mass_1
  - mass_2
  - iso_1
  - iso_2
  - beta_1
  - beta_2
  - bphi_1
  - bphi_2
  - bpt_1
  - bpt_2
  - btag_value_1
  - btag_value_2
  - deltaR_ditaupair
  - eta_1
  - eta_2
  - jeta_1
  - jeta_2
  - jphi_1
  - jphi_2
  - jpt_1
  - jpt_2
  - m_vis
  - met
  - metphi
  - mjj
  - mt_2
  - mt_tot
  - nbtag
  - njets
  - pfmet
  - pfmetphi
  - phi_1
  - phi_2
  - pt_dijet
  - pt_tt
  - pt_ttjj
  - pt_vis
